import {
  Equipment,
  ExerciseDefinition,
  MuscleGroup,
  TrackingType,
} from "./domain";

const builtInExercise = (
  slug: string,
  name: string,
  primaryMuscleGroup: MuscleGroup,
  equipment: Equipment,
  trackingType: TrackingType = "weight_reps",
  secondaryMuscleGroups: MuscleGroup[] = [],
): ExerciseDefinition => ({
  id: `builtin:${slug}`,
  name,
  primaryMuscleGroup,
  secondaryMuscleGroups,
  equipment,
  source: "builtin",
  trackingType,
});

const catalog = [
  builtInExercise(
    "machine-chest-press",
    "Machine Chest Press",
    "Chest",
    "Machine",
    "weight_reps",
    ["Triceps", "Shoulders"],
  ),
  builtInExercise(
    "incline-smith-machine-press",
    "Incline Smith Machine Press",
    "Chest",
    "Smith Machine",
    "weight_reps",
    ["Shoulders", "Triceps"],
  ),
  builtInExercise("pec-deck", "Pec Deck", "Chest", "Machine"),
  builtInExercise(
    "machine-shoulder-press",
    "Machine Shoulder Press",
    "Shoulders",
    "Machine",
    "weight_reps",
    ["Triceps"],
  ),
  builtInExercise(
    "lat-pulldown",
    "Lat Pulldown",
    "Back",
    "Cable Machine",
    "weight_reps",
    ["Biceps"],
  ),
  builtInExercise(
    "seated-cable-row",
    "Seated Cable Row",
    "Back",
    "Cable Machine",
    "weight_reps",
    ["Biceps"],
  ),
  builtInExercise(
    "reverse-pec-deck",
    "Reverse Pec Deck",
    "Shoulders",
    "Machine",
    "weight_reps",
    ["Back"],
  ),
  builtInExercise("lateral-raise", "Lateral Raise", "Shoulders", "Dumbbells"),
  builtInExercise("biceps-curl", "Biceps Curl", "Biceps", "Dumbbells"),
  builtInExercise("hammer-curl", "Hammer Curl", "Biceps", "Dumbbells"),
  builtInExercise(
    "rope-triceps-pushdown",
    "Rope Triceps Pushdown",
    "Triceps",
    "Cable Machine",
  ),
  builtInExercise(
    "leg-press",
    "Leg Press",
    "Quadriceps",
    "Machine",
    "weight_reps",
    ["Glutes"],
  ),
  builtInExercise(
    "smith-machine-squat",
    "Smith Machine Squat",
    "Quadriceps",
    "Smith Machine",
    "weight_reps",
    ["Glutes", "Hamstrings"],
  ),
  builtInExercise(
    "romanian-deadlift",
    "Romanian Deadlift",
    "Hamstrings",
    "Dumbbells",
    "weight_reps",
    ["Glutes"],
  ),
  builtInExercise("leg-extension", "Leg Extension", "Quadriceps", "Machine"),
  builtInExercise(
    "seated-leg-curl",
    "Seated Leg Curl",
    "Hamstrings",
    "Machine",
  ),
  builtInExercise(
    "hip-thrust",
    "Hip Thrust",
    "Glutes",
    "Smith Machine",
    "weight_reps",
    ["Hamstrings"],
  ),
  builtInExercise(
    "glute-bridge",
    "Glute Bridge",
    "Glutes",
    "Bodyweight",
    "weight_reps",
    ["Hamstrings"],
  ),
  builtInExercise(
    "bulgarian-split-squat",
    "Bulgarian Split Squat",
    "Quadriceps",
    "Dumbbells",
    "weight_reps",
    ["Glutes"],
  ),
  builtInExercise(
    "reverse-lunge",
    "Reverse Lunge",
    "Quadriceps",
    "Dumbbells",
    "weight_reps",
    ["Glutes"],
  ),
  builtInExercise(
    "walking-lunge",
    "Walking Lunge",
    "Quadriceps",
    "Dumbbells",
    "weight_reps",
    ["Glutes"],
  ),
  builtInExercise(
    "step-up",
    "Step-Up",
    "Quadriceps",
    "Dumbbells",
    "weight_reps",
    ["Glutes"],
  ),
  builtInExercise("hip-abduction", "Hip Abduction", "Glutes", "Machine"),
  builtInExercise("calf-raise", "Calf Raise", "Calves", "Machine"),
  builtInExercise("cable-crunch", "Cable Crunch", "Core", "Cable Machine"),
  builtInExercise("knee-raise", "Knee Raise", "Core", "Bodyweight", "reps"),
  builtInExercise("plank", "Plank", "Core", "Bodyweight", "duration"),
] satisfies ExerciseDefinition[];

export const builtInExercises: Readonly<Record<string, ExerciseDefinition>> =
  Object.fromEntries(catalog.map((exercise) => [exercise.id, exercise]));
